// <auto-generated />
using System;
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Nicolas.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20241016133221_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Nicolas.Folha", b =>
                {
                    b.Property<int>("FolhaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("FGTS")
                        .HasColumnType("REAL");

                    b.Property<int?>("FuncionarioID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("INSS")
                        .HasColumnType("REAL");

                    b.Property<double>("IRRF")
                        .HasColumnType("REAL");

                    b.Property<int>("ano")
                        .HasColumnType("INTEGER");

                    b.Property<int>("mes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<double>("salarioBruto")
                        .HasColumnType("REAL");

                    b.Property<double>("salarioLiquido")
                        .HasColumnType("REAL");

                    b.Property<double>("valor")
                        .HasColumnType("REAL");

                    b.HasKey("FolhaID");

                    b.HasIndex("FuncionarioID");

                    b.ToTable("Folhas");
                });

            modelBuilder.Entity("Nicolas.Funcionario", b =>
                {
                    b.Property<int>("FuncionarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cpf")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.HasKey("FuncionarioID");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("Nicolas.Folha", b =>
                {
                    b.HasOne("Nicolas.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioID");

                    b.Navigation("Funcionario");
                });
#pragma warning restore 612, 618
        }
    }
}
